### PR TITLE
Some additions to the german translation.

### PR DESCRIPTION
**Pull request by Kaligule**
Also remove some trailing whitespace.

### CODE REVIEW

**Comment by 00-Evan** [comment]
Hey, thanks for helping with translations!

Unfortunately, I don't accept pull requests, all translations are handled through transifex: https://www.transifex.com/shattered-pixel/shattered-pixel-dungeon/

**Comment by Kaligule** [comment]
Thats a shame. Perhaps it would be a good idea to have some contributing guide.

**Comment by 00-Evan** [comment]
Well the contribution guide would just be "I don't accept any". I would turn off pull requests if I could, but github doesn't currently have that functionality.

Please don't think that your translation efforts are wasted though, it shouldn't be too troublesome to put them on transifex. You can search by key, which would let you find exactly the phrases you've translated here.

**Comment by Kaligule** [comment]
I see. Honestly I think it would still help. Perhaps you could add something in the Readme like "Well I don't accept pull requests but here is a link to pixel dungeon, which does".

**Comment by 00-Evan** [comment]
Pixel Dungeon also does not accept pull requests, as far as I'm aware Watabou does not reply to anything posted to his repositories.

**Pull request closed without merging**
