### PR TITLE
generalize quick slot logic

### PR DESCRIPTION
**Pull request by trebor**
this PR should have not direct changes to current game behavior but is intended to lay the ground-work for adding more quick slots in the future.   changes:

  - create a single source of truth for slot count
  - generalize all the logic (that i could find) that involves quick slots
  - add an explicit max slot count currently 12
  - extend the strings in windows.properties to support 12 slots

i have tested the UI with values for `QuickSlot.QUICKSLOT_COUNT` as large as 12 on the desktop version, which appears to all work well.

once this PR is merged i intend to start exploring ways to increase the slot count that would work across all platforms.

### CODE REVIEW

**Comment by 00-Evan** [comment]
Thank you for the effort, but I'm afraid I don't accept pull requests. I don't allow contributions as Shattered is primarily a solo project, and due to potential complications with the GPLv3 license.

The current quickslot system (internally) already allows an arbitrary number of slots, and changes are mainly needed on the UI side of things to support more. The main reason I haven't added more slots is due to UI layout concerns and because I don't want to further encourage the player to keep track of a large number of frequently used items, as 4 is already plenty. I'd prefer to address the demand for more slots by giving players other ways to use or consolidate items.

**Comment by trebor** [comment]
understood.  i guess i will on the fork then. :)

a few questions:

- as per GPL3, i am happy, (and fully expected) that the changes would be rolled into the existing license structure of the project.  i am happy to formally state in any way that would make you comfortable.

- this PR does NOT change quick slot count, which remains at 4.  it does generalized the logic so that future quick slot changes would be much less work.  it might be worth it to peek at the diffs to see how i did that.

in any case this is your project, and if you want keep going on your own i understand that.

  -trebor

**Comment by 00-Evan** [comment]
Sorry, I know it must be frustrating to put in this work and then just get brickwalled. If Github let me disable pull requests without also disabling issues I would do so. I should probable set up a simple CONTRIBUTING.md file to try and preempt cases like this.

Regarding the GPL license, the main issue is that being a contributor to the project gives you certain rights in relation to the distribution of the game which you could use in a manner that's harmful to the project. For instance, the iOS Appstore, and arguably Google Play, violate the GPL due to the nature of how they distribute applications. If you were a contributor, you could complain to these appstores that your rights under the license are being infringed, and potentially get the app taken down. In particular, Apple (I do hope to release on iOS one day) has a history of honoring such requests, probably most famously in the case of VLC media player for iOS.

**Comment by trebor** [comment]
thanks for the details!  and this totally makes sense.  it might be helpful to put up something like:

   WARNING: this project does not accept pull requests...

in the read me?

in any case, i am happy to poke along in my fork.   thanks!

**Comment by lofcz** [comment]
@00-Evan have you considered requiring CLA to be signed before a PR can be merged? It's a standard procedure to solve the issues you've mentioned and for example all official .NET repositories are set up this way. There's an extension you can simply enable on the repository, takes 15 mins to set it up and you can start accepting PRs.

**Comment by 00-Evan** [comment]
@lofcz I'm not really confident that having contributors sign a CLA overrides the terms of the GPLv3 license. Keep in mind that I am not the original creator of PD, so I'm not able to offer Shattered under different license terms.

Even so, it just seems like more trouble than it's worth, especially when I'd prefer for Shattered to be a solo project.

**Pull request closed without merging**
