### PR TITLE
Fix a typo in actors_de.properties and update translation of

### PR DESCRIPTION
**Pull request by spixi**
items_de.properties

### CODE REVIEW

**Comment by TheYsconator** [comment]
Heya! Thanks for helping out by translating! Translations, however, are not handled through github, but rather through transifex. You can find shattered on transifex here:

https://www.transifex.com/shattered-pixel/shattered-pixel-dungeon/

I predict Evan will be asking you to implement the changes on there.

**Comment by spixi** [comment]
Thank you. This can be closed. I will suggest the most changes (including wrong usage of „Sie“) to . The comma changes and capitalized „Du“ are only cosmetic and not required but for consistency.

**Comment by TheYsconator** [comment]
Oh you can just add all the improvements you can think of to Transifex! (I mean, even the cosmetic changes would improve the game.)

Thanks again!

**Comment by 00-Evan** [comment]
As others have mentioned, transifex is the place to go. Those translations are coped into every release of the game, which includes the source code here.

**Pull request closed without merging**
