### PR TITLE
F-Droid Link

### PR DESCRIPTION
**Pull request by FrostKiwi**
This game is a FOSS success story, thought it would be appropriate to show off the F-Droid link as well with a banner.
Using the other banners as a template, I created a banner for F-Droid as well and inserted it next to the "Get it on Google Play Store" banner.
[Get it on F-Droid](https://f-droid.org/en/packages/com.shatteredpixel.shatteredpixeldungeon)
I am fully aware, that the repo takes no Pull requests, but since this isn't code, I though I drop this here.

Thanks for the countless hours of fun.

### CODE REVIEW

**Comment by Sarius997** [comment]
F-Droid isn't shown there as it is an unofficial, unsupported redistribution.

For more context you can search for f-droid in the closed issues here.

**Comment by FrostKiwi** [comment]
> F-Droid isn't shown there as it is an unofficial, unsupported redistribution.
> 
> For more context you can search for f-droid in the closed issues here.

Thanks for the context!
That was not obvious from the first glance, considering the https://f-droid.org/en/packages/com.shatteredpixel.shatteredpixeldungeon/ points here and there is a patreon link https://www.patreon.com/ShatteredPixel

**Comment by 00-Evan** [comment]
The game already has a big bolded warning at the top of the F-Droid descrption. It was put there on my request, mainly so I would stop getting innundated with emails from annoyed F-Droid users every time I released an update, as F-Droid would often take a week or more to get it.

**Comment by FrostKiwi** [comment]
> big bolded warning at the top

Totally missed that! My attention span needs old school flashing marque warnings apparently.

Always played Shattered Pixel Dungeon via F-Droid. Actually the way I initially discovered it all those years ago, when it popped up at the very top, as F-Droid does discoverability via update frequency. Quite sad you get flack for slow update times, F-Droid should communicate `Updates may take up to a week, as all Apps are recompiled to ensure FOSS-ness` more clearly to the users.

Just started a new play-through. Totally enjoying all the new character pixel art, non-chip-tune music and new mechanics like guessing and fire altar.

**Pull request closed without merging**
